version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
    - "3000:3000"
    command: npm start

  backend:
    build:
      context: ./backend
    depends_on:
      - frontend
    volumes:
      - ./backend:/app
      - ./frontend/build:/app/frontend/build # Mount the frontend build directory
    ports:
      - "5000:5000"
    command: npm run dev
